AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - db/schema.rb
    - config/**/*.rb

# Metrics
Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 6

Metrics/LineLength:
  Enabled: true
  Max: 100
  AllowHeredoc: true
  IgnoredPatterns: ['#.*']

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

# Style
Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/ModuleFunction:
  EnforcedStyle: extend_self

# Lint
Lint/AmbiguousOperator:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false
